### ISSUE TITLE
Microsoft account linking (for MC) doesn't work

### ISSUE THREAD

**Issue by FrostedGeulleisia** [cyyynthia/pronoundb.org#53]
Tried two separate browsers, logged in and out of my Microsoft account several times, and made sure I'm connecting it to the correct account (one I have MC on), but every single time I get this rather generic error message.
![image](https://user-images.githubusercontent.com/27410260/160873779-43020d0f-328e-4930-87ff-5cb2ebafaa4a.png)
The fact it doesn't work on neither Firefox nor Chrome makes me think it's not on my end.
Sure, it's probably an issue on Microsoft's end, but I simply can't know with a message as generic as that, as I can log into the aforementioned account just fine, so I'm not sure why it can't authenticate,
It's the only link that I'm having issues with (that corresponds to a platform I actually use).

**Comment by cyyynthia** [comment]
> I simply can't know with a message as generic as that

That's the "goal" here, to have a generic message that doesn't give information about an attacker about what could have gone wrong if they're attempting to attack the authentication flow. It makes troubleshooting for end users a bit more annoying though, especially when bugs start to sneak in, which is likely what's going on, considering the Minecraft authentication via Microsoft is *very* cumbersome (and consist of some reverse-engineered parts).

I just pushed & deployed a few small tweaks, can you see if these help or not at all?

**Comment by FrostedGeulleisia** [comment]
Unfortunately it still doesn't appear to work, same error at the same point (after hitting "Yes" on the Microsoft prompt to connect the account)

**Comment by FrostedGeulleisia** [comment]
Update:
Didn't notice this until now, but I *did* actually recieve an email telling me the app was successfully granted access, so it's probably not on their end.
![Screenshot_2022-03-31-12-04-43-11](https://user-images.githubusercontent.com/27410260/161031006-8355f076-f857-44d8-be99-c1689c6f7e11.jpg)

**Comment by cyyynthia** [comment]
It's unfortunately for the case of Minecraft account linking more complicated; while I had no doubt the OAuth2 authentication was working fine, once you authorized PronounDB to access your account I have to:
 - forward this authentication to Xbox Live servers;
 - get a new authorization from Xbox Live servers to authenticate to Minecraft auth servers;
 - authenticate to Minecraft auth servers.

This process is rather complex, and the issue is arising somewhere here. The lack of clear documentation from Microsoft is making things tougher, and the issue is probably due to a quirk of Xbox Live that is unexpected in my authentication flow. I'll try to investigate this deeper and find what's going on.

**Comment by FrostedGeulleisia** [comment]
Alright, I understand that it's quite the process.
If you need me to try anything, let me know.

**Comment by cyyynthia** [comment]
I've added a bit more error reporting when it made sense, but I'm fairly confident the auth process is correctly implemented. Can you give it a shot, and see if the error you get is a bit more specific as what may be your issue?

**Comment by FrostedGeulleisia** [comment]
Alright so, turns out it's an issue inherently caused by Microsoft's trash policies that I wasn't ever informed of.
Being in the void of "ok you're almost legal but also not" = you have to deal with crap like this
![obraz](https://user-images.githubusercontent.com/27410260/161329037-9f3f7a61-9b93-4723-b420-2e4cebfeb35f.png)

**Comment by cyyynthia** [comment]
Aw yeah, it's something that happens with third party apps like PronounDB. I unfortunately can't do anything about this as far as I'm aware, and I wasn't even aware of this possibility before I saw the error code & its description during my exploration of how the authentication works.

Sorry this happens to you, but I'm going to close this issue. Thanks for raising the point that authentication errors clearly lacked clear information, as there are errors which indeed deserved being disclosed to the user.
